MONGODB_URI = "mongodb://chelonium.cmbi.umcn.nl"
MONGODB_DB_NAME = "whynot"
COMMENTS_DIRECTORY = "/srv/data/scratch/whynot2/comment"
WHYNOT_HSSP_DIRECTORY = "/srv/data/scratch/whynot2/hssp"
SPROT_FASTA = "/srv/data/uniprot/uniprot_sprot.fasta"
TREMBL_FASTA = "/srv/data/uniprot/uniprot_trembl.fasta"
